### PR TITLE
Add covariance regulator

### PR DESCRIPTION
**Pull request by t0maboro**
Just to decrease a chance for ending with singular matrix, problem was with covariance which was converging to 0. In some cases (especially with much noise or totally random data), results might be worse, because of the regulator's impact.

### CODE REVIEW

**Comment by gregori0o** [comment]
Do you have any link to a website with more information on why this regularization works?

**Comment by t0maboro** [comment]
> Do you have any link to a website with more information on why this regularization works?

https://stats.stackexchange.com/questions/219302/singularity-issues-in-gaussian-mixture-model - second answer

Note that I modified regulator that was used there a bit, but also tried to follow that idea.

And used it only in the place where the MVN instance is created.

**Review by mhawryluk — APPROVED** [review]
Seems to work great now for the generated data! Awesome 😃

**Review by gregori0o — APPROVED** [review]
LGTM!

**Pull request merged**
